name: tbep
services:
  neo4j:
    image: neo4j:5.26-enterprise
    container_name: neo4j
    restart: 'always'
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_transaction_total_max=0
      - NEO4J_dbms_security_procedures_unrestricted=gds*
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./scripts:/var/lib/neo4j/import/
      - ../neo4j/data:/var/lib/neo4j/data

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: bhupesh42/tbep-frontend:pdnet-saipuram-com
    container_name: frontend
    env_file:
      - frontend/.env
    restart: 'always'
    ports:
      - "3000:80"

  gsea:
    build: 
      context: gsea
      dockerfile: Dockerfile
    container_name: gsea
    restart: 'always'
    ports:
      - "5000:5000"
  
  nestjs:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: nestjs
    # Change this if running on local to avoid restarting on failure
    restart: 'always'
    ports:
      - "4000:4000"
    depends_on:
      - neo4j
      - redis
      - clickhouse
    env_file:
      - backend/.env
  
  redis:
    image: redis:8.2-alpine
    container_name: redis
    restart: 'always'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-cache:/data

  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: clickhouse
    restart: always   
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./scripts/data/backup:/backup
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

volumes:
  redis-cache:
  clickhouse-data: